services:
  flask-app:
    image: pawkol/web_plus_base:front
    deploy:
      replicas: 4
    ports:
      - "9999:8080" 
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=numbers_db
    depends_on:
      - mysql-db
    networks:
      - nett

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: numbers_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nett

volumes:
  mysql_data:

networks:
  nett:
    driver: overlay 
